---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  ansible_user: ale.adminlocal
  ansible_password: Cetrox88$
  ansible_port: 5985
  ansible_connection: winrm
  ansible_winrm_server_cert_validation: ignore
  gather_facts: no
  tasks:
    - name: Exécution de la commande PowerShell pour créer une VM
      ansible.windows.win_shell: |
        New-VM -Name "VM-APP-DEMO" -MemoryStartupBytes 5368709120 -Generation 2 -SwitchName "VSwitch_interne_DEMO"
      register: vm_creation_output

    - name: Vérifier la sortie de la création de la VM
      debug:
        var: vm_creation_output.stdout

    - name: Démarrer la VM nouvellement créée
      ansible.windows.win_shell: |
        Start-VM -Name "VM-APP-DEMO"
