---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  gather_facts: no
  become: yes
  become_user: ale.adminlocal
  become_password: Cetrox88$
  become_method: runas
  
  tasks:
    - name: Exécution de la commande PowerShell pour créer une VM
      ansible.windows.win_shell:
       Script : |
          New-VM -Name "VM-APP-DEMO" -MemoryStartupBytes 5368709120 -Generation 2 -SwitchName "VSwitch_interne_DEMO"

