---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  gather_facts: no
  tasks:
    - name: Vérifier l'existence des vSwitch
      ansible.windows.win_shell: | 
         Get-VMSwitch -SwitchType Internal
      register: internal_vswitch_check
      failed_when: internal_vswitch_check.rc != 0

    - name: Vérifier l'existence des vSwitch connectés à une carte réseau
      ansible.windows.win_shell: |
         Get-VMSwitch -SwitchType External
      register: external_vswitch_check
      failed_when: external_vswitch_check.rc != 0

    - name: Créer un vSwitch interne s'il n'existe pas
      ansible.windows.win_shell: |
        New-VMSwitch -Name "VSwitch_interne_DEMO" -SwitchType Internal
      when: internal_vswitch_check.rc != 0

    - name: Créer un vSwitch connecté à une carte réseau s'il n'existe pas
      ansible.windows.win_shell: New-VMSwitch -Name "VSwitch_externe_DEMO" -SwitchType External -NetAdapterName "Nom_carte_reseau"
      when: external_vswitch_check.rc != 0

    - name: Créer la machine virtuelle avec 4 vCPU et disque principal dans le répertoire VM
      ansible.windows.win_shell: |
        $VMName = "VM-APP-DEMO"
        New-VM -Name $VMName -MemoryStartupBytes 5368709120 -Generation 1 -SwitchName "VSwitch_externe_DEMO" -SwitchName "VSwitch_interne_DEMO" -Path "N:\VM\$VMName"
        Set-VMProcessor -VMName $VMName -Count 4
        New-VHD -Path "N:\VM\$VMName\Disk\VM-APP-DEMO.vhdx" -SizeBytes 10GB
        Add-VMHardDiskDrive -VMName $VMName -Path "N:\VM\$VMName\VM-APP-DEMO.vhdx"
      register: vm_creation_output

    - name: Vérifier la sortie de la création de la VM
      debug:
          var: vm_creation_output.stdout

    - name: Créer le disque secondaire dans le répertoire Hyper-V
      ansible.windows.win_shell: |
        New-VHD -Path "N:\VM\$VMName\Disque_secondaire.vhdx" -SizeBytes 10GB
        Add-VMHardDiskDrive -VMName $VMName -Path "N:\VM\$VMName\Disque_secondaire.vhdx"










    - name: Exécution de la commande PowerShell pour créer une VM
      ansible.windows.win_shell: |
        New-VM -Name "VM-APP-DEMO" -MemoryStartupBytes 5368709120 -Generation 1 -SwitchName "VSwitch_interne_DEMO" -SwitchName "VSwitch_externe_DEMO"
        Set-VMProcessor -VMName "VM-APP-DEMO" -Count 4
      register: vm_creation_output

    - name: Vérifier la sortie de la création de la VM
      debug:
        var: vm_creation_output.stdout

    - name: Démarrer la VM nouvellement créée
      ansible.windows.win_shell: |
        Start-VM -Name "VM-APP-DEMO"
