---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        $SwitchLan = 'vSwitch From NIC1'
        $SwitchInterne = 'vSwitch Interne'

        $commutateursVirtuels = Get-VMSwitch

        $existe = $false
        foreach ($vSwitch in $commutateursVirtuels) {
            if ($vSwitch.Name -eq $SwitchInterne -and $vSwitch.SwitchType -eq "Internal") {
                $existe = $true
                break
            }
        }

        if (-not $existe) {
            New-VMSwitch -Name $SwitchInterne -SwitchType Internal -Notes "For Evolucare Imaging Internal VMs"
            New-NetIPAddress -IPAddress 10.42.42.1 -InterfaceAlias "vEthernet (vSwitch Interne)"
            Disable-NetAdapterBinding -InterfaceAlias "vEthernet (vSwitch Interne)" -ComponentID ms_tcpip6

            Write-Host "Le commutateur $SwitchInterne a ete cree avec succes."
        } else {
            Write-Host "Le commutateur $SwitchInterne existe deja."
        }

- name: Create Virtual Machines
  hosts: windows_hosts
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        # Insérez ici le reste du script de création de machines virtuelles...

- name: Download and Unzip Master Images
  hosts: windows_hosts
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        # Insérez ici les commandes de téléchargement et de dézippage...

- name: Convert Virtual Hard Disks
  hosts: windows_hosts
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        # Insérez ici les commandes de conversion des disques durs virtuels...

- name: Attach Virtual Hard Disks to VM
  hosts: windows_hosts
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        # Insérez ici les commandes d'attachement des disques aux machines virtuelles...

- name: Clean Up
  hosts: windows_hosts
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        # Insérez ici les commandes de nettoyage...

- name: Start Virtual Machines
  hosts: windows_hosts
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        Start-VM $VMsnameAPP
        Start-VM $VMsnameBDD
