---
- name: Création d'une VM-APP et d'un vSwitch dans Hyper-V
  hosts: all
  gather_facts: no

  tasks:
  - name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
    win_shell: |
    New-VM -Name "VM-APP-DEMO" -MemoryStartupBytes 5368709120 -Generation 2 -SwitchName "VSwitch_interne_DEMO"
