---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        New-Item "M:\HYPERV\" -itemType Directory
        New-Item "N:\HYPERV\" -itemType Directory
        
        $SwitchLan = 'vSwitch From NIC1'
        $SwitchInterne = 'vSwitch Interne'

        $commutateursVirtuels = Get-VMSwitch

        $existe = $false
        foreach ($vSwitch in $commutateursVirtuels) {
            if ($vSwitch.Name -eq $SwitchInterne -and $vSwitch.SwitchType -eq "Internal") {
                $existe = $true
                break
            }
        }

        if (-not $existe) {
            New-VMSwitch -Name $SwitchInterne -SwitchType Internal -Notes "For Evolucare Imaging Internal VMs"
            New-NetIPAddress -IPAddress 10.42.42.1 -InterfaceAlias "vEthernet (vSwitch Interne)"
            Disable-NetAdapterBinding -InterfaceAlias "vEthernet (vSwitch Interne)" -ComponentID ms_tcpip6

            Write-Host "Le commutateur $SwitchInterne a ete cree avec succes."
        } else {
            Write-Host "Le commutateur $SwitchInterne existe deja."
        }

    - name: Execute PowerShell script
      win_shell: |
        $VMsnameAPP= "VM-IMGPRD-APP"
        $cpuAPP= 2
        $ramAPP= 10GB
        $PathVMAPP= "M:\HYPERV\"
        $PathVMAPPDISK4= "N:\HYPERV\"
        new-vm -Name $VMsnameAPP -MemoryStartupBytes $ramAPP -Generation 1 -Switchname $SwitchLan -Path $PathVMAPP 
        Set-VM -Name $VMsnameAPP -ProcessorCount $cpuAPP -StaticMemory -CheckpointType Disabled -AutomaticStopAction Shutdown -AutomaticStartAction Start -AutomaticStartDelay 20
        Add-VMNetworkAdapter -VMName $VMsnameAPP -SwitchName $SwitchInterne
        New-Item "$PathVMAPP\$VMsnameAPP\Virtual Hard Disks" -itemType Directory
        $VMsnameBDD= "VM-IMGPRD-BDD"
        $cpuBDD= 2
        $ramBDD= 10GB
        $PathVMBDD= "D:\HYPERV\"
        new-vm -Name $VMsnameBDD -MemoryStartupBytes $ramBDD -Generation 1 -Switchname $SwitchLan -Path $PathVMBDD 
        Set-VM -Name $VMsnameBDD -ProcessorCount $cpuBDD -StaticMemory -CheckpointType Disabled -AutomaticStopAction Shutdown -AutomaticStartAction Start -AutomaticStartDelay 0
        Add-VMNetworkAdapter -VMName $VMsnameBDD -SwitchName $SwitchInterne
        New-Item "$PathVMBDD\$VMsnameBDD\Virtual Hard Disks" -itemType Directory

    - name: Execute PowerShell script
      win_shell: |
        $URIAPP="https://downloads-imaging.evolucare.com/masters/IMGPRD-APPv9.1_master/IMGPRD-APP9.1_MASTER_HV.zip"
        $URIBDD="https://downloads-imaging.evolucare.com/masters/IMGPRD-BDDv9.1_master/IMGPRD-BDD9.1_MASTER_HV.zip"
        $pair = "$('DownloadsMaster'):$('1Y6fhgt?MQ?InkR#75UWy1TujTNN?Sf&5bvE#BnX')"
        $encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
        $basicAuthValue = "Basic $encodedCreds"
        $Headers = @{
          	Authorization = $basicAuthValue
        }
        Measure-Command { Invoke-WebRequest -Uri $URIAPP -OutFile "$PathVMAPP$VMsnameAPP\Virtual Hard Disks\IMGPRD-APP9.1_MASTER_HV.zip" -Headers $Headers
        }
        Measure-Command { Invoke-WebRequest -Uri $URIBDD -OutFile "$PathVMBDD$VMsnameBDD\Virtual Hard Disks\IMGPRD-BDD9.1_MASTER_HV.zip" -Headers $Headers
        }
        Expand-Archive -LiteralPath $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\IMGPRD-APP9.1_MASTER_HV.zip" -DestinationPath $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\" -Force
        Expand-Archive -LiteralPath $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\IMGPRD-BDD9.1_MASTER_HV.zip" -DestinationPath $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\" -Force
        Convert-VHD -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\MASTER-IMGPRD-APP9.1-disk1.vhd" -DestinationPath $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\"$VMsnameAPP"-disk1-fixe.vhdx" -VHDType Fixed
        Convert-VHD -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\MASTER-IMGPRD-APP9.1-disk2.vhd" -DestinationPath $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\"$VMsnameAPP"-disk2-fixe.vhdx" -VHDType Fixed
        Convert-VHD -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\MASTER-IMGPRD-APP9.1-disk3.vhd" -DestinationPath $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\"$VMsnameAPP"-disk3-fixe.vhdx" -VHDType Fixed
        Convert-VHD -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\MASTER-IMGPRD-APP9.1-disk4.vhd" -DestinationPath $PathVMAPPDISK4$VMsnameAPP\"Virtual Hard Disks\"$VMsnameAPP"-disk4-dyn.vhdx" -VHDType Dynamic
        Convert-VHD -Path $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\MASTER-IMGPRD-BDD9.1-disk1.vhd" -DestinationPath $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\"$VMsnameBDD"-disk1-fixe.vhdx" -VHDType Fixed
        Convert-VHD -Path $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\MASTER-IMGPRD-BDD9.1-disk2.vhd" -DestinationPath $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\"$VMsnameBDD"-disk2-fixe.vhdx" -VHDType Fixed
        Add-VMHardDiskDrive -VMName $VMsnameAPP -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\$VMsnameAPP-disk1-fixe.vhdx"
        Add-VMHardDiskDrive -ControllerType SCSI -VMName $VMsnameAPP -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\$VMsnameAPP-disk2-fixe.vhdx"
        Add-VMHardDiskDrive -ControllerType SCSI -VMName $VMsnameAPP -Path $PathVMAPP$VMsnameAPP\"Virtual Hard Disks\$VMsnameAPP-disk3-fixe.vhdx"
        Add-VMHardDiskDrive -ControllerType SCSI -VMName $VMsnameAPP -Path $PathVMAPPDISK4$VMsnameAPP\"Virtual Hard Disks\$VMsnameAPP-disk4-dyn.vhdx"
        Add-VMHardDiskDrive -VMName $VMsnameBDD -Path $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\$VMsnameBDD-disk1-fixe.vhdx"
        Add-VMHardDiskDrive -ControllerType SCSI -VMName $VMsnameBDD -Path $PathVMBDD$VMsnameBDD\"Virtual Hard Disks\$VMsnameBDD-disk2-fixe.vhdx"
        
    - name: Execute PowerShell script
      win_shell: |
        rm $PathVMAPP$VMsnameAPP\"Virtual Hard Disks"\IMGPRD-APP9.1_MASTER_HV.zip -r -Force
        rm $PathVMBDD$VMsnameBDD\"Virtual Hard Disks"\IMGPRD-BDD9.1_MASTER_HV.zip -r -Force
        rm $PathVMAPP$VMsnameAPP\"Virtual Hard Disks"\*.vhd -r -Force
        rm $PathVMBDD$VMsnameBDD\"Virtual Hard Disks"\*.vhd -r -Force

    - name: Execute PowerShell script
      win_shell: |
        Start-VM $VMsnameAPP
        Start-VM $VMsnameBDD
