---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Exécution de la commande PowerShell pour créer une VM
      ansible.windows.win_shell: >
        New-VM -Name "VM-APP-DEMO" -MemoryStartupBytes 5368709120 -Generation 2 -SwitchName "VSwitch_interne_DEMO"
      register: vm_creation_output

    - name: Démarrer la VM nouvellement créée
      ansible.windows.win_shell: >
        Start-VM -Name "VM-APP-DEMO"
