---
- name: Créer une nouvelle VM-APP dans Hyper-V avec PowerShell
  hosts: all
  gather_facts: no
  vars:
    vcpu: "2"
    vram: "4096"
    vm_location: "C:\\HyperV\\VMs"
    disk_location: "C:\\HyperV\\Disks"
    
  tasks:
    - name: Create VM directory
      win_shell: New-Item -Path "{{ vm_location }}" -ItemType Directory

    - name: Create Disk directory
      win_shell: New-Item -Path "{{ disk_location }}" -ItemType Directory

    - name: Create VM
      win_shell: New-VM -Name MyVM -MemoryStartupBytes {{ vram }} -Path "{{ vm_location }}" -NewVHDPath "{{ disk_location }}/MyDisk.vhdx" -NewVHDSizeBytes 10GB -SwitchName "YourVirtualSwitchName"

