---
- name: Créer une nouvelle VM-IMGPRD-HUB dans Hyper-V
  hosts: all
  gather_facts: no
  vars:
    VMName: "VM-IMGPRD-HUB"
    VMPath: "N:\\HYPERV\\"
    VMCpu: "2"
    VMRam: "2GB"
    SwitchInterne: "vSwitch Interne"
    URLHUB: "https://downloads-imaging.evolucare.com/masters/IMGPRD-HUBv3_master/IMGPRD-HUB_MASTER_HV.zip"
       
  tasks:
    - name: Création des vSwitch Interne
      ansible.windows.win_shell: |
        New-VMSwitch -Name "{{ SwitchInterne }}" -SwitchType Internal -Notes "For Evolucare Imaging Internal VMs"
        New-NetIPAddress -IPAddress 10.42.42.1 -InterfaceAlias "vEthernet ({{ SwitchInterne }})"
        Disable-NetAdapterBinding -InterfaceAlias "vEthernet ({{ SwitchInterne }})" -ComponentID ms_tcpip6

    - name: Créer la machine virtuelle avec 2 vCPU et disque principal dans le répertoire VM
      ansible.windows.win_shell: |
        New-VM -Name "{{ VMName }}" -MemoryStartupBytes 2147483648 -Generation 1 -SwitchName "{{ SwitchInterne }}" -Path "{{ VMPath }}"
        Set-VM -Name "{{ VMName }}" -ProcessorCount "{{ VMCpu }}"
        New-Item "{{ VMPath }}{{ VMName }}\\Virtual Hard Disks" -ItemType Directory
      register: vm_creation_output

    - name: Téléchargement du Master, Conversion vHDX et Intégration
      ansible.windows.win_shell: |
       $username = "a.lenglet"
       $password = ConvertTo-SecureString "Armand@3279!" -AsPlainText -Force
       $cred = New-Object System.Management.Automation.PSCredential ($username, $password)

       $url = "{{ URLHUB }}"
       $vmPath = "{{ VMPath }}"
       $vmName = "{{ VMName }}"
       $destination = "$vmPath$vmName\\Virtual Hard Disks\\IMGPRD-HUB_MASTER_HV.zip"
       $destPath = "$vmPath$vmName\\Virtual Hard Disks\\"

       if (!(Test-Path -Path $destPath)) {
         New-Item -ItemType Directory -Path $destPath -Force
       }

       ansible.windows.win_get_url:
        url: "{{ URLHUB }}"
        url_username: "{{ cred.UserName }}"
        url_password: "{{ cred.Password }}"
        dest: "{{ destination }}"

      Expand-Archive -LiteralPath "{{ destPath }}IMGPRD-HUB_MASTER_HV.zip" -DestinationPath "{{ destPath }}" -Force



  
           
    - name: Vérifier la sortie de la création de la VM
      debug:
          var: vm_creation_output.stdout

    - name: Démarrer la VM nouvellement créée
      ansible.windows.win_shell: |
        Start-VM -Name "{{ VMName }}"
