---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=apache2 state=latest
    - name: start nginx
      service:
          name: apache2
          state: started
